name: fl
description: Flutter run helper with auto reload and dart:developer logs.
version: 0.1.0
repository: https://github.com/azliR/dart_fl

executables:
  fl: fl

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.7.0
  path: ^1.9.0
  vm_service: ^15.0.2
  watcher: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
